name: Docker Image CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Set Up GoLang
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.5
      - name: Install dependencies
        run: go get .
      - name: Build application
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/mpdapp-linux-arm64 ./cmd/rest-api

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/mpdgo-back:latest
            ${{ secrets.DOCKER_USER }}/mpdgo-back:${{ github.sha }}

